[project]
name = "dev"
version = "0.1.0"
description = ""
authors = [
    {name = "phur99",email = "skerrigen12@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "langchain (>=0.3.23,<0.4.0)",
    "langgraph (>=0.3.29,<0.4.0)",
    "langchain-community (>=0.3.21,<0.4.0)",
    "langchain-ollama (>=0.3.1,<0.4.0)",
    "python-dotenv (>=1.1.0,<2.0.0)",
    "newspaper3k (>=0.2.8,<0.3.0)",
    "lxml-html-clean (>=0.4.2,<0.5.0)",
    "huggingface (>=0.0.1,<0.0.2)",
    "huggingface-hub (>=0.30.2,<0.31.0)",
    "transformers (>=4.51.3,<5.0.0)",
    "torch (>=2.6.0,<3.0.0)",
    "pyzmq (==25.1.1)",
    "openai (>=1.76.0,<2.0.0)",
    "pykakao (>=0.0.7,<0.0.8)",
    "google-auth-oauthlib (>=1.2.1,<2.0.0)",
    "google-auth-httplib2 (>=0.2.0,<1.0.0)",
    "google-api-python-client (>=2.166.0,<3.0.0)",
    "langchain-openai (>=0.3.14,<0.4.0)",
    "youtube-transcript-api (>=1.0.3,<2.0.0)",
    "scikit-learn (>=1.6.1,<2.0.0)",
    "fastapi (==0.115.8)",
    "pydantic (==2.10.6)",
    "qdrant-client[grpc] (>=1.14.2,<2.0.0)",
    "langchain-qdrant (>=0.2.0,<0.3.0)",
    "datasets (>=3.6.0,<4.0.0)",
    "pytest (>=8.3.5,<9.0.0)",
    "anyio (>=4.9.0,<5.0.0)",
    "pytest-asyncio (>=0.26.0,<0.27.0)",
    "pytest-tornasync (>=0.6.0.post2,<0.7.0)",
    "pytest-trio (>=0.8.0,<0.9.0)",
    "pytest-twisted (>=1.14.3,<2.0.0)",
    "twisted (>=24.11.0,<25.0.0)",
    "slowapi (==0.1.9)",
]

[[tool.poetry.source]]
name = "flashinfer"
url = "https://flashinfer.ai/whl/cu124/torch2.6/"
priority = "explicit"

[project.optional-dependencies]
gpu = [
    "vllm (==0.8.5)",
    "triton (==3.2.0)",
]

[tool.poetry.extras]
with-gpu = ["gpu"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


# 아래 섹션은 black의 설정
[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

# 아래 섹션은 flake8의 설정
[tool.flake8]
ignore = "E203, E501, W503"
max-line-length = 88
exclude = ".git,__pycache__,docs/,old/,build/,dist/"
[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
flake8 = "^7.2.0"
